const { findPhoneNumbersInText, parsePhoneNumberFromString } = require('libphonenumber-js');  // phone-number extractor + single-number parser from libphonenumber-js; module parses and extracts phone numbers from text using libphonenumber-js
const SAUDI_MOBILE_RE = /(?<!\d)(?:(?:\+|00)?966[\s-]?|0)5\d{8}(?!\d)/g;  // glued-mobile recovery pattern; findPhoneNumbersInText treats ')' and '-' as phone-internal separators, so a mobile glued to a list marker with no space (e.g. "3)0543294683", "0591648564-1", or two numbers dash-joined "0598547667-0583229298") becomes an over-length token that fails validation and is silently dropped; this bounded token ((+966|00966|966|0) then 5 + 8 digits, non-digit or string edge on both sides) matches mobiles ONLY (starts with 5), so it never introduces landline/toll-free noise
function parser_phone(text) {  // extract phone numbers from a text string; @param {string} text input to search; @returns {Array<string>} numbers in international format (e.g. "+966 50 123 4567"), or [] when none valid
    if (typeof text !== 'string') return [];  // step 1 validate input: reject non-string input with an empty list
    const primary = findPhoneNumbersInText(text, { defaultCountry: 'SA' }).map(m => m.number.formatInternational());  // step 2 primary pass: find every number the library can see (default country 'SA' so local numbers parse correctly) and format each to international form
    const fallback = [...text.replace(/[٠-٩۰-۹]/g, d => d.charCodeAt(0) & 15).matchAll(SAUDI_MOBILE_RE)].map(m => parsePhoneNumberFromString(m[0], 'SA')).filter(p => p && p.isValid()).map(p => p.formatInternational());  // step 3 fallback pass: normalise Arabic-Indic/Extended Arabic-Indic digits to ASCII (low nibble equals the digit value in both ranges), scan for bounded Saudi mobile tokens the primary pass drops, then re-validate so only genuine Saudi mobiles survive (11-digit typos and non-mobiles are rejected)
    return [...new Set([...primary, ...fallback])];  // step 4/5 union both passes, de-duplicating by formatted value while preserving first-seen order (Set keeps insertion order), and return the collected numbers
}  // end parser_phone function
module.exports = parser_phone;  // export the parser
